### ISSUE TITLE
Initial submission

### ISSUE THREAD

**Issue by valgaze** [valgaze/donesun#1]
@codepathreview @codepath : First pass with basic functionality implemented. Will implement polish, styling & extra credit tomorrow nite

**Comment by nesquena** [comment]
Victor,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible.

I wanted to let you know that unfortunately the class is already nearing full at this point, but we are happy to add you to the course waitlist. We will be determining final admittance into the program shortly. For those not admitted as participants, we can also offer access to applicants as a remote observer cohort that has access to the materials and is able to work on the projects at their own pace.

Hope you enjoyed working on the pre-work so far. You are definitely encouraged to continue working on this project now that you've hit the initial pre-work deadline. We'll be following up again with you soon.
